import argparse
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from peat import cli_args, cli_completion
from peat.__main__ import main
from peat.cli_completion import DIR, FILE, NONE, SHELLS, generate_completion


@pytest.fixture(scope="module")
def parser() -> argparse.ArgumentParser:
    return cli_args.build_argument_parser(version="2019.01.01")


@pytest.fixture(scope="module")
def commands(parser):
    return {c.name: c for c in cli_completion._extract(parser)[1]}


def _all_option_strings(parser: argparse.ArgumentParser) -> set[str]:
    subparsers = cli_completion._subparsers_action(parser)
    return {
        flag
        for subparser in subparsers.choices.values()
        for action in subparser._actions
        for flag in action.option_strings
    }


@pytest.mark.parametrize("shell", SHELLS)
def test_generate_completion_includes_all_commands_and_options(parser, shell):
    script = generate_completion(shell, parser, "2019.01.01")
    assert "2019.01.01" in script

    subparsers = cli_completion._subparsers_action(parser)
    for name in subparsers.choices:
        assert name in script

    for flag in _all_option_strings(parser):
        if shell == "fish":  # "complete -l long-name -s s"
            flag = f"-l {flag[2:]}" if flag.startswith("--") else f"-s {flag[1:]}"
        assert flag in script


def test_generate_completion_invalid_shell(parser):
    with pytest.raises(ValueError, match="unsupported shell"):
        generate_completion("tcsh", parser)


def test_extract_aliases(commands):
    assert "encrypt" in commands["encrypt-config"].aliases
    assert "decrypt" in commands["decrypt-config"].aliases
    assert "encrypt" not in commands  # aliases aren't separate commands


def _option(command, flag):
    return next(o for o in command.options if flag in o.flags)


def test_extract_argument_kinds(commands):
    assert _option(commands["parse"], "--config-file").kind == FILE
    assert _option(commands["parse"], "--out-dir").kind == DIR
    assert _option(commands["decrypt-config"], "--write-file").kind == DIR
    assert _option(commands["heat"], "--zeek-dir").kind == DIR
    assert _option(commands["parse"], "--run-name").kind == NONE
    assert _option(commands["parse"], "--verbose").kind is None

    push_type = _option(commands["push"], "--push-type")
    assert push_type.choices == ["config", "firmware"]

    import_modules = _option(commands["scan"], "--import-modules")
    assert import_modules.kind == FILE
    assert import_modules.multi

    assert commands["parse"].positional.kind == FILE
    assert commands["push"].positional.kind == FILE
    assert commands["scan"].positional is None
    assert commands["completion"].positional.choices == list(SHELLS)


def test_completion_command_skips_general_args(commands):
    flags = {f for o in commands["completion"].options for f in o.flags}
    assert flags == {"-h", "--help"}


@pytest.mark.parametrize("shell", SHELLS)
def test_main_completion(mocker, capsys, shell):
    mocker.patch("sys.argv", ["peat", "completion", shell])
    run_peat = mocker.patch("peat.cli_main.run_peat")
    main()
    run_peat.assert_not_called()
    out = capsys.readouterr().out
    assert f'Generated by "peat completion {shell}"' in out


BASH_CASES = [
    (["peat", "pa"], ["parse"]),
    (["peat", "--vers"], ["--version"]),
    (["peat", "parse", "--conf"], ["--config-file"]),
    (["peat", "parse", "-c", "pyproject.to"], ["pyproject.toml"]),
    (["peat", "parse", "README.m"], ["README.md"]),
    (["peat", "push", "-t", ""], ["config", "firmware"]),
    (["peat", "completion", ""], list(SHELLS)),
    (["peat", "encrypt", "--file"], ["--file-path"]),
    (["peat", "decrypt-config", "-w", "tes"], ["tests"]),
    (["peat", "scan", "-I", "README.md", "pyproject.to"], ["pyproject.toml"]),
    (["peat", "scan", "-i", "192.0.2.1", ""], []),
    (["peat", "parse", "--config-file", "=", "pyproject.to"], ["pyproject.toml"]),
]


@pytest.mark.skipif(sys.platform == "win32" or not shutil.which("bash"), reason="requires bash")
@pytest.mark.parametrize(("words", "expected"), BASH_CASES)
def test_bash_completion_script(parser, tmp_path, words, expected):
    script = tmp_path / "peat.bash"
    script.write_text(generate_completion("bash", parser), encoding="utf-8")

    quoted = " ".join(f"'{w}'" for w in words)
    test_script = (
        f"source '{script}'\n"
        f"COMP_WORDS=({quoted})\n"
        f"COMP_CWORD={len(words) - 1}\n"
        "_peat\n"
        'printf "%s\\n" "${COMPREPLY[@]}"\n'
    )
    repo_root = Path(__file__).parent.parent
    result = subprocess.run(
        ["bash", "-c", test_script],
        capture_output=True,
        text=True,
        cwd=repo_root,
        check=True,
    )
    assert result.stdout.split() == expected


@pytest.mark.parametrize(
    ("shell", "check_cmd"),
    [
        ("bash", ["bash", "-n"]),
        ("zsh", ["zsh", "-n"]),
        ("fish", ["fish", "-n"]),
    ],
)
def test_completion_script_syntax(parser, tmp_path, shell, check_cmd):
    if sys.platform == "win32" or not shutil.which(check_cmd[0]):
        pytest.skip(f"{check_cmd[0]} is not installed")

    script = tmp_path / f"peat.{shell}"
    script.write_text(generate_completion(shell, parser), encoding="utf-8")
    subprocess.run([*check_cmd, str(script)], check=True)
