#!/usr/bin/env bash
#
# Usage: sudo bash linux-install-script.sh
#
# NOTE:
#   1. root permissions are required (run with 'sudo')
#   2. man-db must be installed. If not, install via 'sudo apt install man-db'
#   3. Shell tab completions are generated by the installed executable
#      ('peat completion <shell>'). Failures there don't fail the install.

set -ex

SCRIPTDIR="$(dirname $0)"

cp "$SCRIPTDIR"/peat /usr/local/bin/
chmod +rx /usr/local/bin/peat
mkdir -p /usr/local/share/man/man1/
cp "$SCRIPTDIR"/peat.1 /usr/local/share/man/man1/
mandb

# Install tab completions for bash, zsh, and fish (best-effort)
install_completion() {
    mkdir -p "$(dirname "$2")" && /usr/local/bin/peat completion "$1" > "$2" \
        || { rm -f "$2"; echo "WARNING: failed to install $1 tab completion"; }
}
install_completion bash /usr/local/share/bash-completion/completions/peat
install_completion zsh /usr/local/share/zsh/site-functions/_peat
install_completion fish /usr/local/share/fish/vendor_completions.d/peat.fish
