<# 
Install-PEAT.ps1
Downloads PEAT for Windows and installs it for the current user.

Installs to:  $env:LOCALAPPDATA\Programs\peat.exe
Adds to PATH: HKCU:\Environment (user PATH)
Tab completion: $env:LOCALAPPDATA\Programs\peat_completion.ps1, loaded from $PROFILE

Run in a regular (non-admin) PowerShell session.
#>

$ErrorActionPreference = "Stop"

$Repo = "sandialabs/PEAT"
$Url  = "https://github.com/$Repo/releases/latest/download/peat.exe"
$DestDir  = Join-Path $env:LOCALAPPDATA "Programs"
$DestExe  = Join-Path $DestDir "peat.exe"

function Add-ToUserPath([string]$Dir) {
    $regPath = "HKCU:\Environment"
    $name = "Path"

    $current = (Get-ItemProperty -Path $regPath -Name $name -ErrorAction SilentlyContinue).Path
    if (-not $current) { $current = "" }

    # Split PATH entries, normalize trailing slashes, compare case-insensitively
    $parts = $current -split ";" | Where-Object { $_ -and $_.Trim() -ne "" }
    $normalized = $parts | ForEach-Object { $_.Trim().TrimEnd("\") }

    $dirNorm = $Dir.Trim().TrimEnd("\")
    $already = $normalized | Where-Object { $_.Equals($dirNorm, [System.StringComparison]::OrdinalIgnoreCase) }

    if ($already) { return $false }

    $newPath = if ($current.Trim() -eq "") { $dirNorm } else { "$current;$dirNorm" }
    Set-ItemProperty -Path $regPath -Name $name -Value $newPath
    return $true
}

# Ensure destination directory exists
New-Item -ItemType Directory -Path $DestDir -Force | Out-Null

Write-Host "Downloading PEAT from:"
Write-Host "  $Url"
Write-Host "To:"
Write-Host "  $DestExe"

# Download
Invoke-WebRequest -Uri $Url -OutFile $DestExe -UseBasicParsing

# Add install directory to user PATH (so "peat.exe" is runnable as "peat")
$pathUpdated = Add-ToUserPath -Dir $DestDir

if ($pathUpdated) {
    Write-Host "Updated user PATH in registry (HKCU:\Environment)."
    Write-Host "You may need to open a new terminal (or sign out/in) for PATH changes to take effect."
} else {
    Write-Host "User PATH already contains: $DestDir"
}

# Install PowerShell tab completion (best-effort, failures don't fail the install).
# The script is generated by the installed executable, so it matches its version,
# and is loaded from the user's PowerShell profile.
try {
    $CompletionScript = Join-Path $DestDir "peat_completion.ps1"
    & $DestExe completion powershell | Out-File -FilePath $CompletionScript -Encoding utf8
    if ($LASTEXITCODE -ne 0) { throw "peat completion exited with code $LASTEXITCODE" }

    $ProfileLine = ". `"$CompletionScript`""
    if (-not (Test-Path $PROFILE)) {
        New-Item -ItemType File -Path $PROFILE -Force | Out-Null
    }
    if (-not (Select-String -Path $PROFILE -SimpleMatch $ProfileLine -Quiet)) {
        Add-Content -Path $PROFILE -Value $ProfileLine
    }
    Write-Host "Installed tab completion (loaded from $PROFILE)."
} catch {
    Write-Warning "Failed to install tab completion: $_"
}

Write-Host "Installed. Try running: peat --help"

